# password manager
Host keys
    HostName keys.phoenox.net
    User doug

# backup host
Host dump
    HostName hk-s020.rsync.net
    User 20332

# chad-betamax account on github
Host github.com-chad-betamax
    HostName github.com
    User git

